version: '3'

services:
  spark-master:
    build:
      context: ./docker/spark-master
      args:      
        - SPARK_VERSION=3.2.2
        - SPARK_HADOOP_VERSION=3.2
    container_name: master
    environment: 
      - SPARK_MASTER_HOST=master
    ports:
      - 8080:8080
      - 7077:7077
    
  spark-worker-1:
    build:
      context: ./docker/spark-worker
      args:
        - SPARK_VERSION=3.2.2
        - SPARK_HADOOP_VERSION=3.2
    container_name: spark-worker-1
    environment: 
      - SPARK_MASTER_HOST=master
    ports:
      - 8081:8081
    depends_on:
      - spark-master

  spark-worker-2:
    build:
      context: ./docker/spark-worker
      args:
        - SPARK_VERSION=3.2.2
        - SPARK_HADOOP_VERSION=3.2
    container_name: spark-worker-2
    environment: 
      - SPARK_MASTER_HOST=master
    ports:
      - 8082:8081
    depends_on:
      - spark-master

  jupyter-notebook:
    build: 
      context: ./docker/jupyter
      args:
        - SPARK_VERSION=3.2.2
        - SPARK_HADOOP_VERSION=3.2
    container_name: jupyter-spark-runtime
    environment:
      - SPARK_MASTER_HOST=master
    ports:
      - 8989:8989
    depends_on:
      - spark-master