ARG HADOOP_VERSION

FROM hadoop:${HADOOP_VERSION}

# FROM ubuntu:20.04 as base

RUN apt-get clean

ENV TZ="Asia/Jakarta"

ARG SPARK_VERSION
ARG SPARK_HADOOP_VERSION

RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y curl wget software-properties-common python3.8 python3-pip python3-venv

RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y openjdk-8-jdk-headless

ENV JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"

RUN echo ${SPARK_VERSION}

RUN wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz

RUN tar -zxvf spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION} /usr/local/etc/spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION} && \
    mkdir /usr/local/etc/spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}/logs && \
    rm spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz

ENV SPARK_HOME=/usr/local/etc/spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}
ENV PATH="$PATH:${SPARK_HOME}/bin:${SPARK_HOME}/sbin"

ENV SPARK_CONF_DIR="${SPARK_HOME}/conf"
ENV HADOOP_CONF_DIR="${HADOOP_HOME}/etc/hadoop"
ENV YARN_CONF_DIR="${HADOOP_HOME}/etc/hadoop"
ENV SPARK_LOG_DIR="${SPARK_HOME}/logs"
ENV SPARK_PID_DIR="${SPARK_HOME}/tmp"
ENV PYSPARK_PYTHON=/usr/bin/python3
ENV SPARK_MASTER_PORT=7077

COPY conf/spark-defaults.conf $SPARK_HOME/conf


WORKDIR ${SPARK_HOME}

CMD source ~/.bashrc