version: '3.7'

networks:
  bigdata:
    external: true
    driver: bridge
    enable_ipv6: false

services:
  spark-master:
    image: spark-master-yarn:$SPARK_VERSION
    build: 
      context: ./Yarn/image/master
      args:
        - SPARK_VERSION=$SPARK_VERSION
    container_name: spark-master
    restart: always
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - bigdata

  spark-worker:
    image: spark-worker-yarn:$SPARK_VERSION
    build:
      context: ./Yarn/image/worker
      args:
        - SPARK_VERSION=$SPARK_VERSION
    container_name: spark-worker
    environment:
      - SPARK_MASTER_HOST=spark-master
    restart: always
    ports:
      - 8081:8081
    networks:
      - bigdata

  notebook:
    image: spark-notebook-yarn:$SPARK_VERSION
    build:
      context: ./Yarn/image/jupyter
      args:
        - SPARK_VERSION=$SPARK_VERSION
    container_name: jupyter-notebook-yarn
    environment:
      - SPARK_MASTER_HOST=spark-master
    restart: always
    ports:
      - 8989:8989
      - 8990:8990
      - 4040:4040
      - 4041:4041
    networks:
      - bigdata
